spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    title: Backend API Document
    version: v1.0.0
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}

jwt:
  secretKey: abctest